application: dita-generator-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: latest

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: favicon.ico
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: .*
  script: main.py
