application: dita-generator
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: .*
  script: main.py
